# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Area.create(name: '北海道')
Area.create(name: '青森県')
Area.create(name: '岩手県')
Area.create(name: '宮城県')
Area.create(name: '秋田県')
Area.create(name: '山形県')
Area.create(name: '福島県')
Area.create(name: '茨城県')
Area.create(name: '栃木県')
Area.create(name: '群馬県')
Area.create(name: '埼玉県')
Area.create(name: '千葉県')
Area.create(name: '東京都')
Area.create(name: '神奈川県')
Area.create(name: '新潟県')
Area.create(name: '富山県')
Area.create(name: '石川県')
Area.create(name: '福井県')
Area.create(name: '山梨県')
Area.create(name: '長野県')
Area.create(name: '岐阜県')
Area.create(name: '静岡県')
Area.create(name: '愛知県')
Area.create(name: '三重県')
Area.create(name: '滋賀県')
Area.create(name: '京都府')
Area.create(name: '大阪府')
Area.create(name: '兵庫県')
Area.create(name: '奈良県')
Area.create(name: '和歌山県')
Area.create(name: '鳥取県')
Area.create(name: '島根県')
Area.create(name: '岡山県')
Area.create(name: '広島県')
Area.create(name: '山口県')
Area.create(name: '徳島県')
Area.create(name: '香川県')
Area.create(name: '愛媛県')
Area.create(name: '高知県')
Area.create(name: '福岡県')
Area.create(name: '佐賀県')
Area.create(name: '長崎県')
Area.create(name: '熊本県')
Area.create(name: '大分県')
Area.create(name: '宮崎県')
Area.create(name: '鹿児島県')
Area.create(name: '沖縄県')

Genre.create(name: '和食')
Genre.create(name: '洋食')
Genre.create(name: '中華')
Genre.create(name: 'エスニック')
Genre.create(name: 'カレー')
Genre.create(name: '焼肉')
Genre.create(name: '鍋')
Genre.create(name: '居酒屋')
Genre.create(name: 'ダイニングバー')
Genre.create(name: '創作料理')
Genre.create(name: 'ファミレス')
Genre.create(name: 'ラーメン')
Genre.create(name: 'カフェ')
Genre.create(name: 'パン')
Genre.create(name: 'スイーツ')
Genre.create(name: 'お酒')
Genre.create(name: 'スポーツバー')
Genre.create(name: 'ラウンジ')
Genre.create(name: 'ビアガーデン')
